### ISSUE TITLE
5512 operator missing updates? 

### ISSUE THREAD

**Issue by TiloGit** [ibm-ecm/container-samples#31]
Hi, 

the CP4BA version 23.0.2  got already two IF. But fncm 5512 got nothing.  
What is the update plan for fncm deployed via operator on OCP? 

CP4BA: https://github.com/IBM/cloud-pak/blob/master/repo/case/ibm-cp-automation/index.yaml
FNCM:  https://github.com/IBM/cloud-pak/blob/master/repo/case/ibm-cp-fncm-case/index.yaml

@jekahn and @Vincent-Le

**Comment by Vincent-Le** [comment]
@TiloGit - right, that's because CP4BA has a monthly iFix cadence and FNCM has a quarterly iFix.  There will be an iFix for FNCM 5.5.12 at the end of March.

In any case, FNCM support deployment on OCP since 5.5.8.  You can use any version to deploy on OCP.  Make sure you check SPCR for the supported version of OCP.  Here is SPCR for 5.5.12: https://www.ibm.com/software/reports/compatibility/clarity-reports/report/html/softwareReqsForProduct?deliverableId=A2081B37501E4E4986F36E931CCB4537&osPlatforms=AIX|Linux|Windows&duComponentIds=S005|S004|S003|S006|S010|S009|S007|S008|S002|C012|C014|C011|C013|C016&mandatoryCapIds=30|9|132|20|26&optionalCapIds=380|12|128|35|19|16|27

**Comment by jekahn** [comment]
Hi @TiloGit!

5.5.12 branch has been updated to 5.5.12IF1. 

You should see some quicker updates in the coming months! 

Best, 

Jason

**Comment by jekahn** [comment]
Hi @TiloGit -- FNCM Standalone has now moved to a monthly release model and you should see updates on the last Wednesday of every month.
